server:
  port: 10010
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10088/eureka
zuul:
  routes:
    SERVICEPROVIDER: /SERVICEPROVIDER/**
    SERVICECONSUMER: /SERVICECONSUMER/**
#      path: /SERVICEPROVIDER/**
#      serviceId: serviceProvider